# This is a yaml file -- be careful when editing
# Stick to the formatting
# List the markdown files you want to build into a pdf
# List them in ORDER
# One file per line


input-files:
- README.md #You will want to remove this file
- CheckList.md #You will NOT want to remove this file
